# Generated by Django 3.0.8 on 2021-11-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(unique=True)),
                ('file_size', models.IntegerField(null=True)),
                ('movie_format', models.TextField(null=True)),
                ('bitrate', models.IntegerField(null=True)),
                ('screen_size', models.TextField(null=True)),
                ('duration', models.IntegerField(default=0)),
                ('original_title', models.TextField()),
                ('title', models.TextField()),
                ('id_tmdb', models.IntegerField(null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('file_status', models.TextField()),
                ('release_year', models.IntegerField(default=0)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField()),
                ('name', models.TextField()),
                ('extension', models.TextField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='movie.Movie')),
            ],
            options={
                'unique_together': {('job', 'name', 'movie')},
                'ordering': ('movie', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_tmdb', models.TextField()),
                ('poster', models.ImageField(null=True, upload_to='posters/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='movie.Movie')),
            ],
            options={
                'ordering': ('movie',),
                'unique_together': set(),
            },
        ),
    ]
